import XCTest
@testable import Mila

/// Run the real multi-speaker fixture (generated by
/// `scripts/generate-audio-fixture.sh`) through `UtteranceDetector` and
/// assert it actually catches the conversation. Fast (no whisper, no
/// audio capture chain), deterministic (same fixture every run),
/// catches the "barely picks up only some words" symptom that the
/// loopback UI test would hide behind BlackHole / TCC fragility.
@MainActor
final class UtteranceDetectorFixtureTests: XCTestCase {

    /// Where the fixture script writes by default.
    private let fixturePath = "/tmp/mila-test-fixture.wav"

    /// Repo root used to locate the generator script. Tests run with
    /// `cwd` inside DerivedData on CI; the repo path is exported via
    /// the env var the workflow sets, falling back to the build-time
    /// SRCROOT for local runs.
    private var repoRoot: String {
        if let v = ProcessInfo.processInfo.environment["MILA_REPO_ROOT"] { return v }
        // `#file` of this test resolves to `…/MilaTests/UtteranceDetectorFixtureTests.swift`.
        return (#file as NSString)
            .deletingLastPathComponent
            .replacingOccurrences(of: "/MilaTests", with: "")
    }

    override func setUp() async throws {
        try await super.setUp()
        if !FileManager.default.fileExists(atPath: fixturePath) {
            let script = "\(repoRoot)/scripts/generate-audio-fixture.sh"
            guard FileManager.default.fileExists(atPath: script) else {
                throw XCTSkip("Fixture generator not found at \(script)")
            }
            let proc = Process()
            proc.executableURL = URL(fileURLWithPath: "/bin/bash")
            proc.arguments = [script, fixturePath]
            let pipe = Pipe()
            proc.standardOutput = pipe
            proc.standardError = pipe
            try proc.run()
            proc.waitUntilExit()
            guard proc.terminationStatus == 0,
                  FileManager.default.fileExists(atPath: fixturePath) else {
                let out = String(data: pipe.fileHandleForReading.readDataToEndOfFile(),
                                 encoding: .utf8) ?? ""
                throw XCTSkip("Fixture generation failed: \(out)")
            }
        }
    }

    func test_fixture_emits_cover_most_of_the_conversation() throws {
        let samples = try loadFixture(path: fixturePath)
        let fixtureDur = Double(samples.count) / 16_000
        XCTAssertGreaterThan(fixtureDur, 40, "Fixture should be at least 40s; got \(fixtureDur)s")

        let detector = UtteranceDetector()
        var emits: [(samples: [Float], startSec: Double)] = []
        detector.onUtterance = { s, start in emits.append((s, start)) }

        // Pump in 30ms chunks — same rate the audio engine produces.
        let chunk = 480
        var offset = 0
        while offset < samples.count {
            let end = min(offset + chunk, samples.count)
            detector.ingest(samples[offset..<end])
            offset = end
        }
        detector.flush()

        // The fixture has 14 lines separated by 600ms silences. After
        // hysteresis we don't expect each line to be its own emit (some
        // adjacent lines merge across the 600ms gap if their energy
        // tail keeps the detector latched), but we DO expect a healthy
        // spread of emits across the timeline.
        let emitCount = emits.count
        let durs = emits.map { Double($0.samples.count) / 16_000 }
        let totalDur = durs.reduce(0, +)
        let startSeconds = emits.map { $0.startSec }
        print("FixtureTest: fixture=\(fixtureDur)s emits=\(emitCount) totalEmit=\(totalDur)s")
        for (i, e) in emits.enumerated() {
            print(String(format: "  emit[%2d]: start=%6.2fs dur=%5.2fs", i, e.startSec, durs[i]))
        }

        // 1. Coverage: total emit duration should be at least 35% of
        //    the fixture (true speech is ~50-60%, plus pre-roll, minus
        //    inter-line silences that the detector should NOT capture).
        XCTAssertGreaterThan(
            totalDur, fixtureDur * 0.35,
            "Emit coverage \(totalDur)s / fixture \(fixtureDur)s — VAD dropped too much speech"
        )

        // 2. Emit count: at least 8 emits across the 14 lines. Fewer
        //    means the detector is merging too aggressively (silenceMs
        //    too high) or dropping below min (minUtteranceMs too high).
        XCTAssertGreaterThanOrEqual(
            emitCount, 8,
            "Only \(emitCount) emit(s) — most short lines (Hi/Yes/OK/Done/Great) were dropped"
        )

        // 3. Dispersion: emits should span at least 70% of the fixture.
        //    If all emits cluster in the first half, the noise floor
        //    or hysteresis drifted and stopped catching later speech.
        let firstStart = startSeconds.first ?? 0
        let lastStart = startSeconds.last ?? 0
        XCTAssertGreaterThan(
            lastStart - firstStart, fixtureDur * 0.7,
            "Emits cluster (\(firstStart)..\(lastStart) of \(fixtureDur)s) — detector stopped catching late audio"
        )

        // 4. No single emit should run to the max-cap unless it
        //    legitimately exhausted a long sentence. With 600ms
        //    inter-line pauses the detector should split, not run on.
        let maxAllowable = 18.0  // maxUtteranceMs is 20s; cushion 2s
        for (i, dur) in durs.enumerated() {
            XCTAssertLessThan(
                dur, maxAllowable,
                "Emit #\(i) (\(dur)s) hit/neared the max-cap — detector failed to split on the 600ms pauses"
            )
        }
    }

    // MARK: - WAV loading

    /// Minimal 16-bit PCM mono WAV loader. The fixture is generated by
    /// `afconvert -d LEI16@16000 -c 1` so we know the layout — no need
    /// for AVFoundation for this.
    private func loadFixture(path: String) throws -> [Float] {
        let data = try Data(contentsOf: URL(fileURLWithPath: path))
        // Skip the 44-byte canonical WAV header. afconvert emits a
        // standard fmt + data chunk for LEI16 mono so this offset is
        // reliable for our generator. If we ever switch tooling, this
        // will need to parse chunks properly.
        let pcmOffset = 44
        guard data.count > pcmOffset else {
            throw NSError(domain: "loadFixture", code: 1,
                          userInfo: [NSLocalizedDescriptionKey: "WAV too small"])
        }
        let pcm = data.subdata(in: pcmOffset..<data.count)
        let count = pcm.count / 2
        var out = [Float](repeating: 0, count: count)
        pcm.withUnsafeBytes { raw in
            let i16 = raw.bindMemory(to: Int16.self)
            for i in 0..<count {
                out[i] = Float(i16[i]) / 32768.0
            }
        }
        return out
    }
}
